#Write a function mutate to compute all words generated by a single mutation on a given word. A mutation is defined as inserting a character, deleting a character, replacing a character, or swapping 2 consecutive characters in a string. For simplicity consider only letters from a to z.
import string
def mutation(word):
    mutate=set()
    letter=string.ascii_lowercase 
    for i in range(len(word)+1):
        for ch in letter:
            mutate.add(word[:i]+ch+word[i:])#add a character in between the word.

    for i in range(len(word)):
        mutate.add(word[:i] + word[i+1:])#delete a character using word. 

    for i in range(len(word)):
        for ch in letter:
            if word[i] != ch:
                mutate.add(word[:i] + ch + word[i+1:])#replacing characters in the word.
    for i in range(len(word)-1):
                swapped = list(word)
                swapped[i], swapped[i+1] = swapped[i+1], swapped[i]#swapping two values between them without using a third variable.
                mutate.add(''.join(swapped))


    return mutate
mut= mutation("cat")
print(mut)
#{'sat', 'cfat', 'caot', 'caft', 'cagt', 'oat', 'cag', 'cvt', 'cav', 'catw', 'cft', 'czat', 'pcat', 'cjt', 'fat', 'cap', 'hcat', 'czt', }.etc..