#Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.
import string
def mutation(word):
    mutate=set()
    letter=string.ascii_lowercase 
    for i in range(len(word)+1):
        for ch in letter:
            mutate.add(word[:i]+ch+word[i:])#add a character in between the word.

    for i in range(len(word)):
        mutate.add(word[:i] + word[i+1:])#delete a character using word. 

    for i in range(len(word)):
        for ch in letter:
            if word[i] != ch:
                mutate.add(word[:i] + ch + word[i+1:])#replacing characters in the word.
    for i in range(len(word)-1):
                swapped = list(word)
                swapped[i], swapped[i+1] = swapped[i+1], swapped[i]#swapping two values between them without using a third variable.
                mutate.add(''.join(swapped))
    return mutate

def nearly_equal(a,b):
    return a in mutation(b)
 
mut= mutation("cat")
print(mut)
print(nearly_equal("cat", "bat"))  #True
print(nearly_equal("cat", "caat"))  #True
print(nearly_equal("cat", "at"))    #True
print(nearly_equal("cat", "act"))   #True
print(nearly_equal("cat", "cutie")) #False